// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID              uuid.UUID        `json:"id"`
	TrackingID      pgtype.UUID      `json:"tracking_id"`
	VisitorID       string           `json:"visitor_id"`
	EventType       string           `json:"event_type"`
	Url             pgtype.Text      `json:"url"`
	Referrer        pgtype.Text      `json:"referrer"`
	Country         string           `json:"country"`
	Browser         string           `json:"browser"`
	OperatingSystem string           `json:"operating_system"`
	Details         []byte           `json:"details"`
	Timestamp       pgtype.Timestamp `json:"timestamp"`
}

type User struct {
	ID         uuid.UUID   `json:"id"`
	TrackingID pgtype.UUID `json:"tracking_id"`
	Email      string      `json:"email"`
}
