// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	FindOrCreateUser(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
