// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	GetOrCreateUser(ctx context.Context, email string) (uuid.UUID, error)
	GetReferrals(ctx context.Context, arg GetReferralsParams) ([]GetReferralsRow, error)
	GetUserByTrackingID(ctx context.Context, trackingID uuid.UUID) (User, error)
	GetUserTrackingID(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
