// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package database

import (
	"context"

	types "github.com/ScMofeoluwa/minalytics/types"
	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (
  visitor_id, tracking_id, event_type, url, referrer, country, browser, device, operating_system, details, timestamp
) VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, CURRENT_TIMESTAMP )
`

type CreateEventParams struct {
	VisitorID       string             `json:"visitor_id"`
	TrackingID      uuid.UUID          `json:"tracking_id"`
	EventType       string             `json:"event_type"`
	Url             *string            `json:"url"`
	Referrer        *string            `json:"referrer"`
	Country         string             `json:"country"`
	Browser         string             `json:"browser"`
	Device          string             `json:"device"`
	OperatingSystem string             `json:"operating_system"`
	Details         types.EventDetails `json:"details"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.VisitorID,
		arg.TrackingID,
		arg.EventType,
		arg.Url,
		arg.Referrer,
		arg.Country,
		arg.Browser,
		arg.Device,
		arg.OperatingSystem,
		arg.Details,
	)
	return err
}

const findOrCreateUser = `-- name: FindOrCreateUser :one
INSERT INTO users (
  email
) VALUES ( $1 )
ON CONFLICT ( email ) DO UPDATE
SET email = EXCLUDED.email
RETURNING id
`

func (q *Queries) FindOrCreateUser(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findOrCreateUser, email)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const findUserByTrackingID = `-- name: FindUserByTrackingID :one
SELECT id, tracking_id, email FROM users WHERE users.tracking_id = $1
`

func (q *Queries) FindUserByTrackingID(ctx context.Context, trackingID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByTrackingID, trackingID)
	var i User
	err := row.Scan(&i.ID, &i.TrackingID, &i.Email)
	return i, err
}
