definitions:
  main.APIStatus:
    properties:
      message:
        type: string
    type: object
  main.App:
    properties:
      created_at:
        type: string
      name:
        type: string
      trackingID:
        type: string
    type: object
  main.AppResponse:
    properties:
      data:
        $ref: '#/definitions/main.App'
      message:
        type: string
    type: object
  main.BrowserResponse:
    properties:
      data:
        $ref: '#/definitions/main.BrowserStats'
      message:
        type: string
    type: object
  main.BrowserStats:
    properties:
      browser:
        type: string
      percentage:
        type: integer
    type: object
  main.CountryResponse:
    properties:
      data:
        $ref: '#/definitions/main.CountryStats'
      message:
        type: string
    type: object
  main.CountryStats:
    properties:
      country:
        type: string
      percentage:
        type: integer
    type: object
  main.CreateAppRequest:
    properties:
      name:
        type: string
    type: object
  main.DeviceResponse:
    properties:
      data:
        $ref: '#/definitions/main.DeviceStats'
      message:
        type: string
    type: object
  main.DeviceStats:
    properties:
      device:
        type: string
      percentage:
        type: integer
    type: object
  main.OSResponse:
    properties:
      data:
        $ref: '#/definitions/main.OSStats'
      message:
        type: string
    type: object
  main.OSStats:
    properties:
      operating_system:
        type: string
      percentage:
        type: integer
    type: object
  main.PageResponse:
    properties:
      data:
        $ref: '#/definitions/main.PageStats'
      message:
        type: string
    type: object
  main.PageStats:
    properties:
      path:
        type: string
      visitor_count:
        type: integer
    type: object
  main.PageViewResponse:
    properties:
      data:
        $ref: '#/definitions/main.PageViewStats'
      message:
        type: string
    type: object
  main.PageViewStats:
    properties:
      time:
        type: string
      views:
        type: integer
    type: object
  main.ReferralResponse:
    properties:
      data:
        $ref: '#/definitions/main.ReferralStats'
      message:
        type: string
    type: object
  main.ReferralStats:
    properties:
      referrer:
        type: string
      visitor_count:
        type: integer
    type: object
  main.VisitorResponse:
    properties:
      data:
        $ref: '#/definitions/main.VisitorStats'
      message:
        type: string
    type: object
  main.VisitorStats:
    properties:
      time:
        type: string
      visitors:
        type: integer
    type: object
info:
  contact: {}
  description: Analytics API for tracking and managing app data.
  title: Minalytics API
  version: "1.0"
paths:
  /analytics/browsers:
    get:
      consumes:
      - application/json
      description: Retrieves browser stats
      parameters:
      - description: app tracking ID
        in: query
        name: trackingID
        required: true
        type: string
      - description: start date
        in: query
        name: startDate
        type: string
      - description: end date
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: stats fetched successfully
          schema:
            $ref: '#/definitions/main.BrowserResponse'
        "400":
          description: invalid request paramaters
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch browsers
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get Browsers
      tags:
      - Analytics
  /analytics/countries:
    get:
      consumes:
      - application/json
      description: Retrieves country stats
      parameters:
      - description: app tracking ID
        in: query
        name: trackingID
        required: true
        type: string
      - description: start date
        in: query
        name: startDate
        type: string
      - description: end date
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: stats fetched successfully
          schema:
            $ref: '#/definitions/main.CountryResponse'
        "400":
          description: invalid request paramaters
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch countries
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get Countries
      tags:
      - Analytics
  /analytics/devices:
    get:
      consumes:
      - application/json
      description: Retrieves device stats
      parameters:
      - description: app tracking ID
        in: query
        name: trackingID
        required: true
        type: string
      - description: start date
        in: query
        name: startDate
        type: string
      - description: end date
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: stats fetched successfully
          schema:
            $ref: '#/definitions/main.DeviceResponse'
        "400":
          description: invalid request paramaters
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch devices
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get Devices
      tags:
      - Analytics
  /analytics/os:
    get:
      consumes:
      - application/json
      description: Retrieves operating system stats
      parameters:
      - description: app tracking ID
        in: query
        name: trackingID
        required: true
        type: string
      - description: start date
        in: query
        name: startDate
        type: string
      - description: end date
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: stats fetched successfully
          schema:
            $ref: '#/definitions/main.OSResponse'
        "400":
          description: invalid request paramaters
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch operating systems
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get OS
      tags:
      - Analytics
  /analytics/pages:
    get:
      consumes:
      - application/json
      description: Retrieves page stats
      parameters:
      - description: app tracking ID
        in: query
        name: trackingID
        required: true
        type: string
      - description: start date
        in: query
        name: startDate
        type: string
      - description: end date
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: stats fetched successfully
          schema:
            $ref: '#/definitions/main.PageResponse'
        "400":
          description: invalid request paramaters
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch pages
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get Pages
      tags:
      - Analytics
  /analytics/pageviews:
    get:
      consumes:
      - application/json
      description: Retrieves page views
      parameters:
      - description: app tracking ID
        in: query
        name: trackingID
        required: true
        type: string
      - description: start date
        in: query
        name: startDate
        type: string
      - description: end date
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: stats fetched successfully
          schema:
            $ref: '#/definitions/main.PageViewResponse'
        "400":
          description: invalid request paramaters
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch visitors
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get PageViews
      tags:
      - Analytics
  /analytics/referrals:
    get:
      consumes:
      - application/json
      description: Retrieves referral stats
      parameters:
      - description: app tracking ID
        in: query
        name: trackingID
        required: true
        type: string
      - description: start date
        in: query
        name: startDate
        type: string
      - description: end date
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: stats fetched successfully
          schema:
            $ref: '#/definitions/main.ReferralResponse'
        "400":
          description: invalid request paramaters
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch referrals
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get Referrals
      tags:
      - Analytics
  /analytics/track:
    get:
      consumes:
      - application/json
      description: Tracks an event based on encoded data
      parameters:
      - description: Base64 encoded event data
        in: query
        name: data
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Event tracked successfully
          schema:
            $ref: '#/definitions/main.APIStatus'
        "400":
          description: Invalid base64 or JSON data
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: Failed to resolve geolocation or track event
          schema:
            $ref: '#/definitions/main.APIStatus'
      summary: Track an event
      tags:
      - Analytics
  /analytics/visitors:
    get:
      consumes:
      - application/json
      description: Retrieves visitors
      parameters:
      - description: app tracking ID
        in: query
        name: trackingID
        required: true
        type: string
      - description: start date
        in: query
        name: startDate
        type: string
      - description: end date
        in: query
        name: endDate
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: stats fetched successfully
          schema:
            $ref: '#/definitions/main.VisitorResponse'
        "400":
          description: invalid request paramaters
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch visitors
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get Visitors
      tags:
      - Analytics
  /apps:
    get:
      consumes:
      - application/json
      description: Retrieves user apps
      produces:
      - application/json
      responses:
        "200":
          description: apps fetched successfully
          schema:
            $ref: '#/definitions/main.AppResponse'
        "401":
          description: userID not found in context
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to fetch apps
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Get Apps
      tags:
      - Apps
    post:
      consumes:
      - application/json
      description: creates an app
      parameters:
      - description: app name
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.CreateAppRequest'
      produces:
      - application/json
      responses:
        "200":
          description: app created successfully
          schema:
            $ref: '#/definitions/main.AppResponse'
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/main.APIStatus'
        "401":
          description: userID not found in context
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to create app
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Create App
      tags:
      - Apps
  /apps/{trackingID}:
    delete:
      consumes:
      - application/json
      description: Updates app by tracking ID
      parameters:
      - description: Tracking ID of the app to delete
        in: path
        name: trackingID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: app successfully deleted
          schema:
            type: string
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/main.APIStatus'
        "401":
          description: userID not found in context
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to delete app
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Delete App
      tags:
      - Apps
    patch:
      consumes:
      - application/json
      description: Updates app by tracking ID
      parameters:
      - description: Tracking ID of the app to delete
        in: path
        name: trackingID
        required: true
        type: string
      - description: app name
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.CreateAppRequest'
      produces:
      - application/json
      responses:
        "200":
          description: app name successfully changed
          schema:
            $ref: '#/definitions/main.AppResponse'
        "400":
          description: invalid request body
          schema:
            $ref: '#/definitions/main.APIStatus'
        "401":
          description: userID not found in context
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: failed to update app
          schema:
            $ref: '#/definitions/main.APIStatus'
      security:
      - BearerAuth: []
      summary: Update App
      tags:
      - Apps
  /auth/{provider}:
    get:
      consumes:
      - application/json
      description: Initiates OAuth authentication with the specified provider and
        returns a JWT token upon successful login.
      parameters:
      - description: OAuth provider (e.g., google, github)
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            type: string
        "400":
          description: Invalid provider or missing provider
          schema:
            $ref: '#/definitions/main.APIStatus'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/main.APIStatus'
      summary: User Sign-In
      tags:
      - Auth
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
