name: Build and run all tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: 1.24.x

        - name: Checkout code
          uses: actions/checkout@v4

        - name: Get and verify dependencies
          run: go mod download && go mod verify

        - name: Build app
          run: go build -o minalytics cmd/server/main.go

        - name: Run tests with coverage
          run:  go test -v $(go list ./... | grep -v -E '/(cmd|mocks|docs)') -covermode=atomic -coverprofile=coverage.txt

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v5
          with:
            fail_ci_if_error: true
            files: ./coverage.txt
            token: ${{ secrets.CODECOV_TOKEN }}
